// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwimpxdjsjbpfsuzoexp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aW1weGRqc2picGZzdXpvZXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MzkzNTIsImV4cCI6MjA4NDAxNTM1Mn0.J3JcaLRY0KvchiPA_46L3HUrmB3HH9cQQSD8I8Dyok8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});